name: Package Application with Pyinstaller

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'screenshot.png'
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - 'gitignore'
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller 
        pip install -r requirements.txt

    - name: Package Application
      run: pyinstaller --onefile --windowed video-to-text.py --add-binary='C:\\hostedtoolcache\\windows\\Python\\3.12.4\\x64\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\Microsoft.CognitiveServices.Speech.core.dll':'.' --icon='video-to-text.ico'

    # - name: Package Application
    #   uses: JackMcKew/pyinstaller-action-windows@main
    #   with:
    #     path: .

    - uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: ./dist/video-to-text.exe